name: Sync Upstream

# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 18 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: rovast/sync-upstream-repo@v0.0.1
        with: 
          upstream_repo: https://github.com/tkashkin/Adwaita-for-Steam # change this
          upstream_branch: master # change this
          downstream_branch: adwaita # change this
          token: ${{ secrets.WORKFLOW_TOKEN }}
          merge_args: allow-unrelated-histories
