name: Sync Upstream

on:
  schedule:
    - cron: '1 18 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.2.0.b
        with: 
          upstream_repo: https://github.com/tkashkin/Adwaita-for-Steam
          upstream_branch: master
          downstream_branch: adwaita
          token: ${{ env.WORKFLOW_TOKEN }}
