name: Sync Files
on:
  push:
    branches:
      - test
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: tkashkin/Adwaita-for-Steam
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
